version: "3.9"
services:
  postgres:
    image: postgres:14
    container_name: grocery_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: groceries
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6
    container_name: grocery_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
