name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2   # Step 1: Checkout your code

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'   # Step 2: Set Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        echo "✅ No tests yet, just checking build!"
